mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^tareas/', include('tareas.urls')),
    url(r'^admin/', admin.site.urls),
]

tareas/urls.py
from django.conf.urls import url

from . import views

app_name = 'tareas'
urlpatterns = [
    url(r'^(?P<l_id>[0-9]+)/$', views.listaTareas, name='listado_tareas'),
    url(r'^(?P<l_id>[0-9]+)/pendiente_tarea$', views.DesmarcarTarea, name='pendiente_tarea'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^crear_lista/$', views.ListaCreateView.as_view(), name='crear_lista'),
    url(r'^(?P<pk>[0-9]+)/modificar_lista$', views.ListaUpdateView.as_view(), name='modificar_lista'),
    url(r'^(?P<pk>[0-9]+)/eliminar_lista$', views.ListaDelete.as_view(), name='eliminar_lista'),
    url(r'^crear_tarea/$', views.TareasCreateView.as_view(), name='crear_tarea'),
    url(r'^(?P<pk>[0-9]+)/modificar_tarea$', views.TareasUpdateView.as_view(), name='modificar_tarea'),
    url(r'^(?P<pk>[0-9]+)/eliminar_tarea$', views.TareasDelete.as_view(), name='eliminar_tarea'),
    url(r'^pendientes/$', views.TareasPendientesView.as_view(), name='pendientes'),
    url(r'^terminadas/$', views.TareasTerminadasMesView.as_view(), name='terminadas'),
    url(r'^pendientes_mes/$', views.TareasPendientesMesView.as_view(), name='pendientes_mes'),
]

tareas/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible  # only if you need to support Python 2
class Lista(models.Model):
    titulo_lista = models.CharField(max_length=200, unique=True)
    fecha_lista = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo_lista

@python_2_unicode_compatible  # only if you need to support Python 2
class Tareas(models.Model):
    id_lista = models.ForeignKey(Lista, on_delete=models.CASCADE)
    titulo_tarea = models.CharField(max_length=200, unique=True)
    estado_tarea = models.BooleanField(default=False)
    descripcion_tarea = models.TextField(help_text='Describe la Tarea', blank=True)
    fecha_creacion_tarea = models.DateTimeField(auto_now_add=True)
    fecha_modificacion_tarea = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.titulo_tarea

tareas/forms.py
from django import forms
from . import models


class DateInput(forms.DateInput):
    input_type = "date"


class ListaForm(forms.ModelForm):
    titulo_lista = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = models.Lista
        fields = ['titulo_lista']


class TareasForm(forms.ModelForm):
    titulo_tarea = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    descripcion_tarea = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))
   

    class Meta:
        model = models.Tareas
        fields = ['id_lista','titulo_tarea','descripcion_tarea']

tareas/views.py
from django.http import Http404
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Lista, Tareas
from django.views import generic
from django.contrib.messages.views import SuccessMessageMixin
from .forms import ListaForm, TareasForm
from django.utils import timezone
import datetime
from django.contrib import messages

def listaTareas(request, l_id):
    try:
        lista = Lista.objects.get(pk=l_id)
    except lista.DoesNotExist:
        raise Http404("La Lista No existe")
    return render(request, 'tareas/listado_tareas.html', {'lista': lista})

def DesmarcarTarea(request, l_id):
    try:
        fecha = timezone.now() - datetime.timedelta(days=30)
        tarea = Tareas.objects.get(pk=l_id)
    except tarea.DoesNotExist:
        raise Http404("La Tarea no exite")
    else:
        if tarea.fecha_creacion_tarea < fecha and tarea.estado_tarea == True:
            messages.add_message(request, messages.ERROR, 'La tarea Tiene mas de 30 dias de CREADA y esta TERMINADA.')
            return HttpResponseRedirect(reverse('tareas:listado_tareas', kwargs={'l_id': tarea.id_lista_id}))
        else:
            if tarea.estado_tarea == True:
                tarea.estado_tarea = False
                tarea.save()
                messages.add_message(request, messages.ERROR, 'Tarea Marcada como Pendiente.')
            else:
                tarea.estado_tarea = True
                tarea.save()
                messages.add_message(request, messages.SUCCESS, 'Tarea Marcada como Terminada.')
            return HttpResponseRedirect(reverse('tareas:listado_tareas', kwargs={'l_id': tarea.id_lista_id}))


class IndexView(generic.ListView):
    template_name = 'tareas/index.html'
    context_object_name = 'listado'

    def get_queryset(self):
        """Return the last five published questions."""
        return Lista.objects.all()


class ListaCreateView(SuccessMessageMixin, generic.CreateView):
    model = Lista
    form_class = ListaForm
    success_url = reverse_lazy('tareas:index')
    success_message = "Lista Creada Con Exito"

class ListaUpdateView(generic.UpdateView):
    model = Lista
    form_class = ListaForm
    success_url = reverse_lazy('tareas:index')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.titulo_lista = self.object.titulo_lista
        self.object.save()
        messages.add_message(self.request, messages.SUCCESS, 'Lista Modificada con exito.')
        return HttpResponseRedirect(self.get_success_url())


class ListaDelete(generic.DeleteView):
    model = Lista
    success_url = reverse_lazy('tareas:index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        messages.add_message(self.request, messages.SUCCESS, 'Lista Eliminada con exito.')
        return HttpResponseRedirect(self.get_success_url())


class TareasCreateView(SuccessMessageMixin, generic.CreateView):
    model = Tareas
    form_class = TareasForm
    success_url = reverse_lazy('tareas:index')
    success_message = "Tarea Creada Con Exito"


class TareasUpdateView(generic.UpdateView):
    model = Tareas
    form_class = TareasForm
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        print("kwargs = %s" % self.kwargs)
        self.object.titulo_tarea = self.object.titulo_tarea
        self.object.estado_tarea = self.object.estado_tarea
        self.object.id_lista = self.object.id_lista
        self.object.descripcion_tarea = self.object.descripcion_tarea
        self.object.save()
        messages.add_message(self.request, messages.SUCCESS, 'Tarea Modificada con exito.')
        return HttpResponseRedirect(reverse('tareas:listado_tareas', kwargs={'l_id': self.object.id_lista_id}))
   

class TareasDelete (generic.DeleteView):
    model = Tareas

    def delete(self, request, *args, **kwargs):
        id_lis = self.get_object().id_lista_id
        self.object = self.get_object()
        self.object.delete()
        messages.add_message(self.request, messages.SUCCESS, 'Tarea Eliminada con exito.')
        return HttpResponseRedirect(reverse('tareas:listado_tareas', kwargs={'l_id': id_lis}))
    

class TareasPendientesView(generic.ListView):
    template_name = 'tareas/reportes.html'
    context_object_name = 'lista'

    def get_queryset(self):
        return Tareas.objects.filter(estado_tarea="False")


class TareasTerminadasMesView(generic.ListView):
    template_name = 'tareas/reportes.html'
    context_object_name = 'lista'

    def get_queryset(self):
        return Tareas.objects.filter(estado_tarea="True", fecha_modificacion_tarea__month=timezone.now().month)


class TareasPendientesMesView(generic.ListView):
    template_name = 'tareas/reportes.html'
    context_object_name = 'lista'

    def get_queryset(self):
        fecha = timezone.now() - datetime.timedelta(days=30)
        return Tareas.objects.filter(estado_tarea="False", fecha_creacion_tarea__lt=fecha)

tareas/templates/tareas/index.html
{% extends 'base.html' %}
{% block container %}
    <h1>{{ algo }}</h1>
    <h1><span class="glyphicon glyphicon-list-alt"> </span> Administrador de Listas</h1>
<bR>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <span></span><a class="btn btn-primary " href="/tareas/crear_lista/"><span class="glyphicon glyphicon-plus"></span>Agregar Lista</a></span>
   <a class="btn btn-success" href="/tareas/crear_tarea/"> <span class="glyphicon glyphicon-th-list"></span> Nueva Tarea</a>
    {% if listado %}
    <br><br>
    <table class="table table table-hover table-bordered">

      <tr><th>Titulo</th><th>Fecha Creacion</th><th>*****</th></tr>
    {% for l in listado %}
      <tr><td><a href="/tareas/{{ l.id }}/">{{ l.titulo_lista }}</a></td><td>{{ l.fecha_lista}}</td><td><a class="btn btn-success glyphicon glyphicon-wrench" href="/tareas/{{ l.id }}/modificar_lista"></a>   <a class="btn btn-danger glyphicon glyphicon-remove" href="/tareas/{{ l.id }}/eliminar_lista"></a></td></tr>
    {% endfor %}
    {% else %}
        <p>No hay Listas Guardadas.</p>
    {% endif %}
{% endblock container %}

tareas/templates/tareas/lista_confirm_delete.html
{% extends "base.html" %}

{% block container %}
<form action="" method="post">{% csrf_token %}

 <div class="panel panel-default active" id="panelvisitante">

 <div class="panel-heading" style="background-color: #A93226;color: white;font-weight: bold;">
   <center> 
   <h3 class="panel-title"><span class="glyphicon glyphicon-remove"></span> Panel de Administracion</h3>
   </center>
 </div>

 <div class="panel-body" style="font-weight: bold;text-align: center;">
    <p>Estas Seguro que Deseas Eliminar El resgistro "{{ object }}"..?</p>
 </div> 

 <div class="panel-footer danger" id="foterpanel">
     <input type="submit" value="Eliminar" class="btn btn-danger glyphicon glyphicon-remove" />
       <a class="btn btn-default" href="/tareas/">Cancelar</a>
 </div>  

 </div>
                            
                      
</form>
{% endblock container %}

tareas/templates/tareas/lista_form.html
{% extends "base.html" %}

{% block container %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Aceptar"/>
      <a class="btn btn-danger" href="/tareas/">Cancelar</a>
 </form>
{% endblock container %}

tareas/templates/tareas/listado_tareas.html
{% extends 'base.html' %}
{% block container %}

<h1><span class="glyphicon glyphicon-th-list"> </span> Administrador de Tareas</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% csrf_token %}


<br><br>
<table class="table table-hover table-bordered">
<tr><th class="warning" colspan="6">Titulo Lista: {{ lista.titulo_lista }}</th></tr>
  <tr class="warning"><th>Titulo</th><th>Fecha Creacion</th><th>Fecha Modificacion</th><th>Descripcion</th><th>Estado</th><th>*****</th></tr>
{% for l in lista.tareas_set.all %}
  <tr><td>{{l.titulo_tarea }}</td><td>{{l.fecha_creacion_tarea }}</td><td>{{l.fecha_modificacion_tarea }}</td><td>{{l.descripcion_tarea }}</td><td>{{l.estado_tarea }}</td><td><a class="btn btn-warning glyphicon glyphicon-wrench" href="/tareas/{{ l.id }}/modificar_tarea"></a>
  <a class="btn btn-danger glyphicon glyphicon-remove" href="/tareas/{{ l.id }}/eliminar_tarea"></a> <a class="btn btn-success glyphicon glyphicon-pencil" href="/tareas/{{ l.id }}/pendiente_tarea"></a> </td></tr>
{% endfor %}
</table>

{% endblock container %}

tareas/templates/tareas/reportes.html
{% extends 'base.html' %}
{% block container %}

<h1><span class="glyphicon glyphicon-th-list"> </span> Reportes</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% csrf_token %}


<br><br>
<table class="table table-hover table-bordered">
<tr class="warning"><th>Titulo</th><th>Fecha Creacion</th><th>Fecha Modificacion</th><th>Descripcion</th><th>Estado</th></tr>

{% for l in lista %}
  <tr><td>{{l.titulo_tarea }}</td><td>{{l.fecha_creacion_tarea }}</td><td>{{l.fecha_modificacion_tarea }}</td><td>{{l.descripcion_tarea }}</td><td>{{l.estado_tarea }}</td></tr>

{% endfor %}

</table>

{% endblock container %}

tareas/templates/tareas/tareas_confirm_delete.html
{% extends "base.html" %}

{% block container %}
<form action="" method="post">{% csrf_token %}

 <div class="panel panel-default active" id="panelvisitante">

 <div class="panel-heading" style="background-color: #A93226;color: white;font-weight: bold;">
   <center> 
   <h3 class="panel-title"><span class="glyphicon glyphicon-remove"></span> Panel de Administracion</h3>
   </center>
 </div>

 <div class="panel-body" style="font-weight: bold;text-align: center;">
    <p>Estas Seguro que Deseas Eliminar El resgistro "{{ object }}"?</p>
 </div> 

 <div class="panel-footer danger" id="foterpanel">
     <input type="submit" value="Eliminar" class="btn btn-danger glyphicon glyphicon-remove" />
       <a class="btn btn-default" href="/tareas/">Cancelar</a>
 </div>  

 </div>
                            
                      
</form>
{% endblock container %}

tareas/templates/tareas/tareas_form.html
{% extends "base.html" %}

{% block container %}
<form action="" method="post">

 <div class="panel panel-default active" id="panelvisitante">

 <div class="panel-heading" style="background-color: #268FA9;color: white;font-weight: bold;">
   <center> 
   <h3 class="panel-title"><span class="glyphicon glyphicon-plus"></span> Agregar Tareas</h3>
   </center>
 </div>

 <div class="panel-body" style="">
       {% csrf_token %}
        {{ form.as_p }}
 </div> 

 <div class="panel-footer danger" id="foterpanel">
     <input class="btn btn-primary" type="submit" value="Aceptar"/>
   
       <a class="btn btn-default" href="/tareas/">Cancelar</a>
 </div>  

 </div>
                            
                      
</form>
{% endblock container %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{{ head_title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    {# <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/darkly/bootstrap.min.css" rel="stylesheet">#}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    {% block extra_head %}

    {% endblock %}

  </head>

  <body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" >Task Manager</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'tareas:index' %}">Lista <span class="sr-only">(current)</span></a></li>
        
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reportes Tareas<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'tareas:pendientes' %}">Pendientes</a></li>
            <li><a href="{% url 'tareas:terminadas' %}">Terminadas del Mes</a></li>
            <li><a href="{% url 'tareas:pendientes_mes' %}">Pendientes Mas de 30 dias</a></li>
            </li>
            
          </ul>
        </li>
      </ul>
  
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <div class="container">
        <br/>
        <br/>
        <br/>
        <br/>

        {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{% if message.tags == 'error' %}danger{% else%}{{ message.tags }}{% endif %} alert-dismissible"{% endif %} role='alert'>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        {{ message }}
                </div>
            {% endfor %}
        </div>
        {% endif %}

        {% block container %}
        {% endblock container %}
    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->




    {% block extra_footer %}

    {% endblock extra_footer %}

  </body>
</html>